name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # github actor is the namespace docker push ghcr.io/NAMESPACE/IMAGE_NAME:latest
  IMAGE_NAME: ${{ github.actor }}/ceklis:latest

jobs:
  test-client:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "./client/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test
  test-server:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "./server/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm test
  build:
    runs-on: ubuntu-22.04
    needs: [test-client, test-server]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/client:latest ./client
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/client:latest

      - name: Build and push server image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/server:latest ./server
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/server:latest

      - name: Build and push nginx image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/nginx:latest ./nginx
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/nginx:latest
